### ISSUE TITLE
統合テストを修正する

### ISSUE THREAD

**Issue by Lysander086** [AnchorOrg/anchor-focus-assistant#51]
以下、起票すべき新しい課題のサンプルテンプレートです。

---

# リソース  
- **データベース:** H2（組み込み）および anchor-db-test（Docker Compose により初期化）  
- **テスト対象:** AuthApiIntegrationTest.kt 内で使用する実際のサービス  
- **Gradle プラグイン:** ローカルテスト環境構築用（必要に応じて追加）

# 説明  
現在、公開エンドポイントの構成ミスにより 403 エラーが発生しています。  
この課題では、以下の変更を行い、実際のデータベーストランザクションを伴う統合テスト環境を構築します。  
1. H2 組み込みデータベースと SQL ファイルを利用して、実際の統合テストを実装する。  
2. AuthApiIntegrationTest.kt でモックの代わりに実サービスを利用し、リアルなデータベーストランザクションを検証する。  
3. Gradle 関連プラグインをインポートし、ローカルテスト環境を構成する。テスト用データベースは docker-compose.yml により初期化される anchor-db-test を使用する。

# メイン  
以下、各ファイルの完全版サンプルを示します。

---

## 1. AuthApiIntegrationTest.kt  
```kotlin
// File: AuthApiIntegrationTest.kt
package com.example.project.integration

import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import javax.sql.DataSource

@SpringBootTest
@ActiveProfiles("test")
class AuthApiIntegrationTest {

    @Autowired
    lateinit var dataSource: DataSource

    @Test
    fun testDatabaseTransaction() {
        // Use the real service to perform integration test with H2 database.
        // SQL initialization and verification logic should be added here.
    }
}
```

---

## 2. build.gradle  
```groovy
// File: build.gradle
plugins {
    id 'org.springframework.boot' version '2.7.0'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}
```

---

## 3. docker-compose.yml  
```yaml
# File: docker-compose.yml
version: '3.8'
services:
  anchor-db-test:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: anchor_test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
```

---

## 4. application-test.yml  
```yaml
# File: src/main/resources/application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
```

---

## 5. schema.sql（必要に応じて SQL 初期化ファイル）  
```sql
-- File: src/main/resources/schema.sql
-- SQL schema initialization for H2 database
CREATE TABLE IF NOT EXISTS example_table (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
```

---

これらの変更により、実際のデータベーストランザクションを伴う統合テスト環境が整い、現行エンドポイントの構成ミスによる 403 エラーの原因究明と解決に繋がります。
